name = "Mutts"
uuid = "4f105e01-9b18-47b8-92a3-3fae8366c3d5"
authors = ["Todd J. Green <todd.green@relational.ai>", "Nathan Daly <nathan.daly@relational.ai"]
version = "0.1.0"

[deps]
IsPurelyImmutable = "2ffa6c9d-15c0-4667-be8d-57f90eb6ec69"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
